### ISSUE TITLE
Craftbook pipe sign on a piston

### ISSUE THREAD

**Issue by sigmaroot** [NoCheatPlus/Issues#201]
**What is the problem? What do you expect to see instead?**

When I place a [pipe] sign on a piston to create a craftbook sign, it is dropped.

**If it can be reproduced please try to explain as detailed as possible (video, text or images are always welcome):**

**a) Does it affect all players on your server?**

No, players with '*' permission are not affected, all others are

**b) Is it easy to reproduce?/Does it always happen?**

Yes, just using craftbook (3.9u8, +WorldEdit depencies) and NCP

**c) Does it also happen if you use a unmoded vanilla client?**

Yes, b)

**Have you made any (noteworthy) changes to the default configuration of NCP?**

No

**Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?**

No, it happens only if NPC activated. If NPC is not active, the craftbook pipe works fine

**What is your NoCheatPlus version? (/ncp version)**
#### Server

git-Paper-772 ~MC: 1.9.4~
  detected: 1.9.4
#### NoCheatPlus

Plugin: 3.14.0-SNAPSHOT-sMD5NET-b989
MCAccess: 1.9.4 / Spigot-CB-1.9_R2
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9
  checks: FastConsume | Gutenberg
  defaults: pvpKnockBackVelocity
Hooks: AllViolations~NCP~ 1.0

**What is your server version? (/ncp version or /version)**

Look above

**Comment by Platinteufel** [comment]
Can't reproduce at all on my server. Why it should be related to ncp? 
If you have "pedantic block checks" in the config enabled, craftbook checks if it is your chest and if not, it will drop the sign with the error "area.permission". You could also disable the [pipe] signs in Craftbook config, if you don't need them. The pipes will work without a sign then.

**Comment by sigmaroot** [comment]
Confirmed.
Error "area.use-permission" is shown up when placing the sign on the piston.
Disabling predantic block checks or advanced block checks is **NO** solution for this issue because I need this in some other cases, for that players can't use some mechanics in some cases.

If you want to reproduce, place a sign on the BOTTOM of the piston. Like this: sign >> [_]==|
On any other side, it works fine. But on bottom, NCP is telling CraftBook that it isn't allowed to place a sign here. Why is NCP prevent that? That doesn't make any sense...

**Comment by asofold** [comment]
Can the blockinteract.visible false positives be reproduced without CraftBook? Could be they fire extra events to ensure region protection grips, but a player could not do what the event is indicating. Does need some research i assume.

This just assuming this isn't an occasional false positive, but it happens every time under those conditions.

**Comment by sigmaroot** [comment]
I dunno how to find that out, I'm sorry :(
With CraftBook enabled, it happens every time.
With CraftBook disabled, I dunno how to test for a blockinteract.visible... Maybe someone else could debug this? :)

**Comment by asofold** [comment]
Oh right, sorry - i usually would appreciate others to help too :), e.g. @MyPictures, but he can't possibly react that fast.

You could activate logging all violations to ingame chat or trace file, by setting so in the allviolations (backend...) section, within the logging.extended section, debugonly must be false then.

Alternatively on-the-fly debugging could be used, but that would create way more output that isn't really needed here.

If you can't do it (now/then), someone else will/should soon-ish.

**Comment by Platinteufel** [comment]
Could you make a screenshot of your construction? As I said, I don't have problems at all with CraftBook & NCP

**Comment by Platinteufel** [comment]
@sigmaroot Seems like you are German too. ;)  I'm still not able to reproduce it on my server. Maybe you could show me your special case?

**Comment by sigmaroot** [comment]
@Platinteufel: Sure, please send me an e-mail (admin@sigmaroot.de) and I will show you that case on my test-server.

**Comment by Platinteufel** [comment]
Done. :)

**Comment by Platinteufel** [comment]
Seems like it depens on the direction of the sign.
**Video:** https://youtu.be/s0d2UUS3a8k
**Debug Logs:** http://pastebin.com/YZ7rH4D3

Thanks @sigmaroot

**Comment by me4502** [comment]
@asofold If Advanced&Pedantic Block Checks are disabled, no extra events are fired. OP specified that disabling them does not fix the issue.

**Comment by Platinteufel** [comment]
@me4502 @asofold I've just got the issue on my server now.
If advanced & pedantic block checks are disabled there is **no violation** from ncp. Seems like it has to do with some craftbook events.

**Comment by me4502** [comment]
CraftBook checks if it's possible for a player to access a chest when advanced block checks is enabled. If not, it doesn't. This issue is about when it's not enabled. CraftBook does nothing out of the ordinary in that case

**Comment by Platinteufel** [comment]
Nope @me4502, it's about when advanced block checks are _enabled_. NCP fires a `blockinteract.visible` for some directions of the sign then. If you're interested you can visit my testserver.

**Comment by Platinteufel** [comment]
This video should make it clear. ;)
https://youtu.be/VIFc9A8xxe8

**Comment by me4502** [comment]
The OP specified it happens when they're disabled. With them enabled the solution would be to disable that specific NCP test, as there is no way to get around the issue without removing functionality.

**Comment by sigmaroot** [comment]
No, I've never said that, not in that way as long as I remember.
Here a table:

`advanced_block_checks = true`
`pedantic_block_checks = true`
`block.interact.visible = true`
**FALSE POSITIVE**

`advanced_block_checks = true`
`pedantic_block_checks = true`
`block.interact.visible = false`
**NO ERROR**

`advanced_block_checks = true`
`pedantic_block_checks = false`
`block.interact.visible = true`
**FALSE POSITIVE**

`advanced_block_checks = true`
`pedantic_block_checks = false`
`block.interact.visible = false`
**NO ERROR**

`advanced_block_checks = false`
`pedantic_block_checks = false`
`block.interact.visible = true`
**NO ERROR**

`advanced_block_checks = false`
`pedantic_block_checks = false`
`block.interact.visible = false`
**NO ERROR**

`advanced_block_checks = false` and `pedantic_block_checks = true` doesn't make any sence, because `pedantic_block_checks` are not performed in this case.

**Comment by Platinteufel** [comment]
That specific NCP test only triggers if advanced block checks are enabled, otherwise it doesn't fire a violation ..

**Comment by me4502** [comment]
Sorry, I thought you said somewhere that this issue was occurring with them disabled.

In this case, the best course of action is to disable the visible check.

**Comment by sigmaroot** [comment]
Yes, that's what I've done and it runs fine, but that's no fix for the general bug / false positive in NCP :)

**Comment by me4502** [comment]
I doubt it, as it'd be caused by an extra event being fired - which is required for the functionality of advanced block checks

**Comment by me4502** [comment]
I've used the NoCheatPlus API to disable NoCheatPlus whilst the checks are taking place, that's probably the best solution possible.

**Comment by Platinteufel** [comment]
Disabeling the whole plugin or only that specific check?

**Comment by me4502** [comment]
It disables all checks that could potentially be an issue

**Comment by asofold** [comment]
The api doesn't enable you to deactivate NCP, afaik :), so i'd assume it to be exemption.

If it can't be reproduced by placing signs,  it'll be a cross-plugin issue. On Craftbook side one could discuss, if they'd like to add 'nocheat.skip' meta data to the player, just during firing the extra block place event (not sure which is extra), ncp exemption api might be performing better, but can't really tell. 

My assumption is, that the event somehow uses placing the sign against a side of the block that is not visible to the player. Perhaps @MyPictures or someone else can produce a debug log of this issue with NCP build 1012 or later.

**Comment by me4502** [comment]
Yes, probably the exemptions feature - I didn't see what it was called. It temporarily exempts the player involved.

**Comment by Platinteufel** [comment]
@asofold http://pastebin.com/U9GhdfFC

**Comment by asofold** [comment]
@Platinteufel Wonderful :). Looks like the block place event uses BlockFace.SELF for placing the chest, i.e. the chest is placed onto/into itself somehow :p.

Setting the block face differently in CraftBook wouldn't be fun, because when you decide for a block to place the chest against, then the block may not be reachable for the player, so you would have to scan for accessible directions and so on ...

Can 1.9/1.10 lead to BlockFace.SELF for players at all? In that case we could just skip checking. Couldn't find ad-hoc, where they process the face, an alternative could also be to guard against that on packet level, but we don't yet hard depend on that, so i'd not prefer that.

**Comment by Platinteufel** [comment]
I'm a bit surprised because of my last video (https://youtu.be/VIFc9A8xxe8). As you can see it depends on the direction I'm looking while placing the sign. 
BlockFace only represents the face of a block, right? But I have no idea at all.
Maybe it would be nice to know which specific CraftBook-Event causes the violation, because it doesn't happen without it.

**Comment by asofold** [comment]
Technically it's a PlayerInteractEvent clicking on a chest. The block-face the chest is clicked on is reported as 'SELF', which is not possible with vanilla clients for chests (afaik).

The looking direction may affect it, as NCP will trace where the player is looking, but i assume the interact event to be artificial, so it can easily happen that some looking directions work and some not.

**Comment by sigmaroot** [comment]
Why are you talking 'bout chests?

**Comment by asofold** [comment]
@sigmaroot The debug log. The event that gets cancelled is a PlayerInteractEvent with clicking on a chest (inside of it, interpreting the BlockFace 'SELF'). Mistakenly wrote 'placed' above, but the event apparently is a PlayerInteractEvent.

**Comment by Platinteufel** [comment]
https://github.com/sk89q/CraftBook/commit/114df3d10898b634a93d6ca08cffd1e73e7bfe1d

**Comment by asofold** [comment]
Looks good !

Exemption is best there, perhaps. In future i'll make it easier to exempt reliably with fewer code (exemption tickets). Such could even allow users to add check types to tickets made by other plugins (provided they add their own plugin-dependent ticket ids).

**Comment by asofold** [comment]
Closing as superseded, in the hope it's been fixed externally :).

**Comment by me4502** [comment]
Yeah should be fixed externally. I went through and added a fair few more things to temporarily disable a few months ago.

**Comment by asofold** [comment]
Thank you.
