### ISSUE TITLE
Elytra does not work correclty in gamemode 1

### ISSUE THREAD

**Issue by Platinteufel** [NoCheatPlus/Issues#266]
Since I've updated to the latest dev build my players can't use the elytra in gamemode 1 since it causes CreativeFly violations. 

Video + debug log:
https://youtu.be/5Ajy09ce9q0
http://pastebin.com/d63Ebjgf

In gamemode 0 (survival) it works without any problems.

**Comment by asofold** [comment]
Does / did increasing the horizontal speed (or even modsprint ~ 1.05) help in any way?

The modeling probably is awful, so it might not fix.

**Comment by Platinteufel** [comment]
Nope, unfortunately it doesn't. :(
Well, the elytra works fine without any problems in gamemode 0 & 2.
Only the checks for the creative gamemode have to be adjusted.

**Comment by asofold** [comment]
That's an important detail to notice.. will have to check code fore that...

**Comment by asofold** [comment]
Have you checked this ticket: https://github.com/NoCheatPlus/Issues/issues/169 ?

Is ignoreallowflight set to true?

**Comment by Platinteufel** [comment]
Yes.

`  moving:
    creativefly:
      active: true
      ignoreallowflight: true
      ignorecreative: false`

**Comment by asofold** [comment]
Possibly slipped past this one.

Was there an issue with setting ignorecreative to true? It'll lead to potential trouble with switching between survivalfly and creativefly checks on occasion, but it might help here.

(The creative flying model is more lenient in terms of where you can move to, so to mitigate the issue temporarily, you could increase the allowed speeds _for the default creative mode model_ - however at the risk of creative mode players flying at those speeds with a cheat client all the time.)

**Comment by asofold** [comment]
Is this fixed with build 1066? Let's regard edge cases in a different ticket (such as shortly touching water/vines: https://github.com/NoCheatPlus/Issues/issues/346).

**Comment by asofold** [comment]
Build 1093 contains a related fix - is gliding set via a plugin? I can't use elytra in creative mode with 1.11.2 (or is allowFlight turned off? Or is there some other trick?) ...

**Comment by Platinteufel** [comment]
allowflight is true, ignoreallowflight: true 
I've tested build 1093 and there are still violations for _NCP: [01:12:53] player.creativefly VL 11  (n5a2m3)_

It's still the same behavior like in the video from the first post.
I can provide a new full debug log if needed :)

**Comment by Platinteufel** [comment]
Also, I don't get your comment 
_"While i can't use the elytra while in creative mode, others might be
able to do so with a plugin."_

You SHOULD be able to glide with an elytra also in Creative mode, but NCP does block it atm.

Maybe this first-person video will explain the issue. ;-)
https://youtu.be/17JhxB6b8Io
The violations you've seen in this video ONLY occur with gamemode **creative**.

**Comment by asofold** [comment]
This comes form people not wanting to spoon-feed :p ... i need a single tap to activate elytra.

Fix will be in build 1095.

**Comment by Platinteufel** [comment]
In creative you need one double tap to change from flying to falling and then one more tab to activate your elytra. :p 
Thank you!

**Comment by asofold** [comment]
Closing as fixed then - edge cases should have individual tickets.
