### ISSUE TITLE
End portals = fly detection

### ISSUE THREAD

**Issue by PhanaticD** [NoCheatPlus/Issues#74]
Using dev build 918 players passing through ender portals causes nocheat fly detection resulting in them getting stuck or moving very jerkily through a end portal

**Comment by asofold** [comment]
@PhanaticD Could you add the output of the 'ncp version' command?

We need server + NCP (+related) information, to ensure what we're dealing with.

**Comment by PhanaticD** [comment]
sure here it is

---- Version information ----
#### Server ####
git-Spigot-db6de12-07c3001 (MC: 1.8.8)
(detected: 1.8.8)
#### NoCheatPlus ####
Plugin: 3.13.6-SNAPSHOT-sMD5NET-b918
MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
Features:
  blocks: BlocksMC1_4(base) | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
  checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
Hooks: AllViolations(NCP) 1.0
#### Related Plugins ####
ProtocolLib v3.6.5-SNAPSHOT-b217

**Comment by MyPictures** [comment]
Cannot reproduce:

[16:33:00 INFO]: ---- Version information ----
[16:33:00 INFO]: #### Server ####
[16:33:00 INFO]: git-PaperSpigot-861d6c6-75593ab ~MC: 1.8.8~
[16:33:00 INFO]:   detected: 1.8.8
[16:33:00 INFO]: #### NoCheatPlus ####
[16:33:00 INFO]: Plugin: 3.13.6-BETA-sMD5NET-b924
[16:33:00 INFO]: MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
[16:33:00 INFO]: Features:
[16:33:00 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
[16:33:00 INFO]:   checks: FastConsume | Gutenberg
[16:33:00 INFO]:   defaults: pvpKnockBackVelocity
[16:33:00 INFO]: Hooks: AllViolations~NCP~ 1.0 | TestNCPHook 1.0
>

Could it be related to ProtocolLib?

**Comment by asofold** [comment]
@MyPictures Did you test with high latency settings yet?

**Comment by PhanaticD** [comment]
still happening with build 925

https://gyazo.com/43bc404304b2a53f6564673609d9655c

the end portal was placed one block above air, and the player jumped up into it and was continuously kicked for flying and tons of nocheat violations

**Comment by MyPictures** [comment]
OOohhh you mean litterly a end portal block. I used the normal end portal and it was fine. Going to have another look soon.

@asofold Also going to consider testing with high latency settings also

**Comment by asofold** [comment]
I couldn't reproduce it locally either, but i made them 3x3 accidentally, need with one portal block only and possibly with high latency.

**Comment by PhanaticD** [comment]
make sure its one block above the ground, also it happens with every player pretty reliably on my server

**Comment by asofold** [comment]
ground - air - portal_block

Is teleporting to the end activated at all?

**Comment by PhanaticD** [comment]
no it is just being passed through

**Comment by tssge** [comment]
I can confirm and reproduce. Very annoying in Skywars because we use end portal blocks in their portals.

**Comment by tssge** [comment]
Here's a video on what happens in game:

https://gfycat.com/AliveDesertedFlatfish

We are using default settings of NoCheatPlus. Version information follows:

07.02 18:28:38 [Server] INFO ---- Version information ----
07.02 18:28:38 [Server] INFO #### Server ####
07.02 18:28:38 [Server] INFO git-Spigot-fdc1440-53fac9f ~MC: 1.8.8~
07.02 18:28:38 [Server] INFO detected: 1.8.8
07.02 18:28:38 [Server] INFO #### NoCheatPlus ####
07.02 18:28:38 [Server] INFO Plugin: 3.13.7-RC-sMD5NET-b925
07.02 18:28:38 [Server] INFO MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
07.02 18:28:38 [Server] INFO Features:
07.02 18:28:38 [Server] INFO blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
07.02 18:28:38 [Server] INFO checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
07.02 18:28:38 [Server] INFO defaults: pvpKnockBackVelocity
07.02 18:28:38 [Server] INFO packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
07.02 18:28:38 [Server] INFO Hooks: AllViolations~NCP~ 1.0
07.02 18:28:38 [Server] INFO #### Related Plugins ####
07.02 18:28:38 [Server] INFO ProtocolLib v3.6.4

**Comment by tssge** [comment]
I did some debugging and it seems that when you go inside an ender portal the check returns this:

16-02-07 19:05:22 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.078 / -0.078, sby=44.76636799395752 (-0.078 / 0.0)
 tags: data_missing

but when it's not ender portal, but instead normal portal, the check is this:

16-02-07 19:05:21 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: onground -> onground, jumpphase: 0, liftoff: NORMAL(3)
 hDist: 0.031(-0.006) / 0.287 , vDist: 0 (0) / 0.6, sby=45.0 (0 / 1.35)

Liftoff seems to be UNKNOWN with ender portal but NORMAL with portal block. I hope this is helpful.

**Comment by tssge** [comment]
I did some debugging and it seems that inside ender portal jumpphase gets reset to 0 after it reaches 2. On normal portal block the jumpphase seems to increment as expected.

This must be somehow related to jump phase resetting in the SurvivalFly check code, maybe?

**Comment by tssge** [comment]
Here is debug information from checks. End portal:
`16-02-07 19:23:02 [FINE] [MOVING] [tssge] Split move 1 (from -> loc):
16-02-07 19:23:02 [FINE] [MOVING] [tssge] MOVE in world world:
Location: -423.2996275981897, 45.0, 191.37687375885417
from: -423.2510784247828, 45.0, 191.37721200127982
to: -423.2996275981897, 45.0, 191.37687375885417
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.0784000015258789,0.0)
16-02-07 19:23:02 [FINE]
from flags: SOLID+GROUND
from below id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to flags: SOLID+GROUND
to below id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:02 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: onground -> onground, jumpphase: 0, liftoff: NORMAL(36)
 hDist: 0.049(-0.016) / 0.287 , vDist: 0 (0) / 0.6, sby=45.0 (0 / 1.35)

16-02-07 19:23:02 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.0 / nf=0.0 | ymax=45.0
16-02-07 19:23:02 [FINE] [MOVING] [tssge] Split move 2 (loc -> to):
16-02-07 19:23:02 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.2996275981897, 45.0, 191.37687375885417
to: -423.3976273348564, 45.0, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.0784000015258789,0.0)
16-02-07 19:23:02 [FINE]
from flags: SOLID+GROUND
from below id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to below id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:02 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: onground -> ---, jumpphase: 0, liftoff: NORMAL(37)
 hDist: 0.098(+0.049) / 0.287 , vDist: 0 (0) / 0.425, sby=45.0 (0 / 1.35)

16-02-07 19:23:02 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.0 / nf=0.0 | ymax=45.0
16-02-07 19:23:02 [FINE] [NET] [tssge] Flying(ground=false,x=-423.4511351972915,y=44.92159999847412,z=191.37664826390375)
16-02-07 19:23:02 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.3976273348564, 45.0, 191.37664826390375
to: -423.4511351972915, 44.92159999847412, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.0784000015258789,0.0)
16-02-07 19:23:02 [FINE]
from below id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:02 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 1, liftoff: NORMAL(0)
 hDist: 0.054(-0.044) / 0.287 , vDist: -0.078 (-0.078) / -0.062, sby=45.0 (-0.078 / 1.35)
 tags: ychdec

16-02-07 19:23:02 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.0 / nf=0.0784 (+0.07840000092983246) | ymax=45.0
16-02-07 19:23:02 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.76636799395752,z=191.37664826390375)
16-02-07 19:23:02 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.4511351972915, 44.92159999847412, 191.37664826390375
to: -423.48035049357446, 44.76636799395752, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.1552320045166016,0.0)
16-02-07 19:23:02 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:02 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 2, liftoff: NORMAL(0)
 hDist: 0.029(-0.024) / 0.287 , vDist: -0.155 (-0.077) / -0.139, sby=45.0 (-0.234 / 1.35)

16-02-07 19:23:02 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.0784 / nf=0.233632 (+0.1552319973707199) | ymax=45.0
16-02-07 19:23:02 [FINE] [NET] [tssge] Flying(ground=false,x=-423.50693641395816,y=44.53584062504456,z=191.37664826390375)
16-02-07 19:23:02 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.76636799395752, 191.37664826390375
to: -423.50693641395816, 44.53584062504456, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.230527368912964,0.0)
16-02-07 19:23:02 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:02 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0.027 / 0.287 hbuf=0 , vDist: -0.231 / 0, sby=44.76636799395752 (-0.231 / 0.0)
 tags: data_missing+vdistrel

16-02-07 19:23:02 [INFO] [VL] [MOVING_SURVIVALFLY] [tssge] VL=23.1(+23.1) distance=0.23 health=20.0/20.0 locationfrom=-423.48, 44.77, 191.38 locationto=-423.51, 44.54, 191.38 tags=data_missing+vdistrel
16-02-07 19:23:02 [FINE] [MOVING] [tssge] Set back to: CraftWorld{name=world}-423.48, 44.766, 191.377
16-02-07 19:23:02 [FINE] [MOVING] [tssge] TP UNKNOWN (set-back): Location{world=CraftWorld{name=world},x=-423.48035049357446,y=44.76636799395752,z=191.37664826390375,pitch=42.146633,yaw=90.13701}
16-02-07 19:23:02 [FINE] [NET] [tssge] Expect ACK on outgoing position: CountableLocation(x=-423.48035049357446,y=44.76636799395752,z=191.37664826390375,pitch=42.146633,yaw=90.13701,count=1)
16-02-07 19:23:02 [FINE] [NET] [tssge] Flying(ground=false,x=-423.5311296022046,y=44.231523797587016,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [NET] [tssge] Incoming packet, interpret as ACK for outgoing position.
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.76636799395752,z=191.37664826390375,pitch=42.146633,yaw=90.13701)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.76636799395752,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.687967992431645,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.76636799395752, 191.37664826390375
to: -423.48035049357446, 44.687967992431645, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.37663049823865513,0.0)
16-02-07 19:23:03 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:03 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.078 / -0.078, sby=44.76636799395752 (-0.078 / 0.0)
 tags: data_missing

16-02-07 19:23:03 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.233632 / nf=0.312032 (+0.312032014131546) | ymax=44.76636799395752
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.532735987915046,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.687967992431645, 191.37664826390375
to: -423.48035049357446, 44.532735987915046, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.44749789698341763,0.0)
16-02-07 19:23:03 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:03 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.155 / 0, sby=44.687967992431645 (-0.155 / 0.0)
 tags: data_missing+vdistrel

16-02-07 19:23:03 [INFO] [VL] [MOVING_SURVIVALFLY] [tssge] VL=38.6(+15.5) distance=0.16 health=20.0/20.0 locationfrom=-423.48, 44.69, 191.38 locationto=-423.48, 44.53, 191.38 tags=data_missing+vdistrel
16-02-07 19:23:03 [INFO] tssge failed SurvivalFly: tried to move unexpectedly. VL 39.
16-02-07 19:23:03 [FINE] [MOVING] [tssge] Set back to: CraftWorld{name=world}-423.48, 44.688, 191.377
16-02-07 19:23:03 [FINE] [MOVING] [tssge] TP UNKNOWN (set-back): Location{world=CraftWorld{name=world},x=-423.48035049357446,y=44.687967992431645,z=191.37664826390375,pitch=42.146633,yaw=90.13701}
16-02-07 19:23:03 [FINE] [NET] [tssge] Expect ACK on outgoing position: CountableLocation(x=-423.48035049357446,y=44.687967992431645,z=191.37664826390375,pitch=42.146633,yaw=90.13701,count=1)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.30220861900208,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.687967992431645, 191.37664826390375
to: -423.48035049357446, 44.30220861900208, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.44749789698341763,0.0)
16-02-07 19:23:03 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:03 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.386 / 0, sby=44.687967992431645 (-0.386 / 0.0)
 tags: data_reset+vdistrel

16-02-07 19:23:03 [INFO] [VL] [MOVING_SURVIVALFLY] [tssge] VL=77.2(+38.6) distance=0.39 health=20.0/20.0 locationfrom=-423.48, 44.69, 191.38 locationto=-423.48, 44.30, 191.38 tags=data_reset+vdistrel
16-02-07 19:23:03 [FINE] [MOVING] [tssge] Set back to: CraftWorld{name=world}-423.48, 44.688, 191.377
16-02-07 19:23:03 [FINE] [MOVING] [tssge] TP UNKNOWN (set-back): Location{world=CraftWorld{name=world},x=-423.48035049357446,y=44.687967992431645,z=191.37664826390375,pitch=42.146633,yaw=90.13701}
16-02-07 19:23:03 [FINE] [NET] [tssge] Expect ACK on outgoing position: CountableLocation(x=-423.48035049357446,y=44.687967992431645,z=191.37664826390375,pitch=42.146633,yaw=90.13701,count=2)
16-02-07 19:23:03 [FINE] [NET] [tssge] Incoming packet, interpret as ACK for outgoing position.
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.687967992431645,z=191.37664826390375,pitch=42.146633,yaw=90.13701)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.687967992431645,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [NET] [tssge] Incoming packet, interpret as ACK for outgoing position.
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.687967992431645,z=191.37664826390375,pitch=42.146633,yaw=90.13701)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.60956799090577,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.687967992431645, 191.37664826390375
to: -423.48035049357446, 44.60956799090577, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.7170746714356033,0.0)
16-02-07 19:23:03 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:03 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.078 / -0.078, sby=44.687967992431645 (-0.078 / 0.0)
 tags: data_missing

16-02-07 19:23:03 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.312032 / nf=0.39043203 (+0.3904320299625397) | ymax=44.687967992431645
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.45433598638917,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.60956799090577, 191.37664826390375
to: -423.48035049357446, 44.45433598638917, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.7811331932098841,0.0)
16-02-07 19:23:03 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:03 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.155 / 0, sby=44.60956799090577 (-0.155 / 0.0)
 tags: data_missing+vdistrel

16-02-07 19:23:03 [INFO] [VL] [MOVING_SURVIVALFLY] [tssge] VL=92.7(+15.5) distance=0.16 health=20.0/20.0 locationfrom=-423.48, 44.61, 191.38 locationto=-423.48, 44.45, 191.38 tags=data_missing+vdistrel
16-02-07 19:23:03 [FINE] [MOVING] [tssge] Set back to: CraftWorld{name=world}-423.48, 44.61, 191.377
16-02-07 19:23:03 [FINE] [MOVING] [tssge] TP UNKNOWN (set-back): Location{world=CraftWorld{name=world},x=-423.48035049357446,y=44.60956799090577,z=191.37664826390375,pitch=42.146633,yaw=90.13701}
16-02-07 19:23:03 [FINE] [NET] [tssge] Expect ACK on outgoing position: CountableLocation(x=-423.48035049357446,y=44.60956799090577,z=191.37664826390375,pitch=42.146633,yaw=90.13701,count=1)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.2238086174762,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.60956799090577, 191.37664826390375
to: -423.48035049357446, 44.2238086174762, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.7811331932098841,0.0)
16-02-07 19:23:03 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:03 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.386 / 0, sby=44.60956799090577 (-0.386 / 0.0)
 tags: data_reset+vdistrel

16-02-07 19:23:03 [INFO] [VL] [MOVING_SURVIVALFLY] [tssge] VL=131.3(+38.6) distance=0.39 health=20.0/20.0 locationfrom=-423.48, 44.61, 191.38 locationto=-423.48, 44.22, 191.38 tags=data_reset+vdistrel
16-02-07 19:23:03 [FINE] [MOVING] [tssge] Set back to: CraftWorld{name=world}-423.48, 44.61, 191.377
16-02-07 19:23:03 [FINE] [MOVING] [tssge] TP UNKNOWN (set-back): Location{world=CraftWorld{name=world},x=-423.48035049357446,y=44.60956799090577,z=191.37664826390375,pitch=42.146633,yaw=90.13701}
16-02-07 19:23:03 [FINE] [NET] [tssge] Expect ACK on outgoing position: CountableLocation(x=-423.48035049357446,y=44.60956799090577,z=191.37664826390375,pitch=42.146633,yaw=90.13701,count=2)
16-02-07 19:23:03 [FINE] [NET] [tssge] Incoming packet, interpret as ACK for outgoing position.
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.60956799090577,z=191.37664826390375,pitch=42.146633,yaw=90.13701)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.60956799090577,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [NET] [tssge] Incoming packet, interpret as ACK for outgoing position.
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.60956799090577,z=191.37664826390375,pitch=42.146633,yaw=90.13701)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.53116798937989,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.60956799090577, 191.37664826390375
to: -423.48035049357446, 44.53116798937989, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-1.0248092696844984,0.0)
16-02-07 19:23:03 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:03 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.078 / -0.078, sby=44.60956799090577 (-0.078 / 0.0)
 tags: data_missing

16-02-07 19:23:03 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.39043203 / nf=0.46883205 (+0.4688320457935333) | ymax=44.60956799090577
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.37593598486329,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.53116798937989, 191.37664826390375
to: -423.48035049357446, 44.37593598486329, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-1.082713105363373,0.0)
16-02-07 19:23:03 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:03 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.155 / 0, sby=44.53116798937989 (-0.155 / 0.0)
 tags: data_missing+vdistrel

16-02-07 19:23:03 [INFO] [VL] [MOVING_SURVIVALFLY] [tssge] VL=146.8(+15.5) distance=0.16 health=20.0/20.0 locationfrom=-423.48, 44.53, 191.38 locationto=-423.48, 44.38, 191.38 tags=data_missing+vdistrel
16-02-07 19:23:03 [FINE] [MOVING] [tssge] Set back to: CraftWorld{name=world}-423.48, 44.531, 191.377
16-02-07 19:23:03 [FINE] [MOVING] [tssge] TP UNKNOWN (set-back): Location{world=CraftWorld{name=world},x=-423.48035049357446,y=44.53116798937989,z=191.37664826390375,pitch=42.146633,yaw=90.13701}
16-02-07 19:23:03 [FINE] [NET] [tssge] Expect ACK on outgoing position: CountableLocation(x=-423.48035049357446,y=44.53116798937989,z=191.37664826390375,pitch=42.146633,yaw=90.13701,count=1)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.14540861595032,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=43.84109178849278,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [NET] [tssge] Incoming packet, interpret as ACK for outgoing position.
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.53116798937989,z=191.37664826390375,pitch=42.146633,yaw=90.13701)
16-02-07 19:23:03 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.53116798937989, 191.37664826390375
to: -423.48035049357446, 44.14540861595032, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-1.082713105363373,0.0)
16-02-07 19:23:03 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:03 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.386 / 0, sby=44.53116798937989 (-0.386 / 0.0)
 tags: data_reset+vdistrel

16-02-07 19:23:03 [INFO] [VL] [MOVING_SURVIVALFLY] [tssge] VL=185.4(+38.6) distance=0.39 health=20.0/20.0 locationfrom=-423.48, 44.53, 191.38 locationto=-423.48, 44.15, 191.38 tags=data_reset+vdistrel
16-02-07 19:23:03 [FINE] [MOVING] [tssge] Set back to: CraftWorld{name=world}-423.48, 44.531, 191.377
16-02-07 19:23:03 [FINE] [MOVING] [tssge] TP UNKNOWN (set-back): Location{world=CraftWorld{name=world},x=-423.48035049357446,y=44.53116798937989,z=191.37664826390375,pitch=42.146633,yaw=90.13701}
16-02-07 19:23:03 [FINE] [NET] [tssge] Expect ACK on outgoing position: CountableLocation(x=-423.48035049357446,y=44.53116798937989,z=191.37664826390375,pitch=42.146633,yaw=90.13701,count=1)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.53116798937989,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [NET] [tssge] Incoming packet, interpret as ACK for outgoing position.
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.53116798937989,z=191.37664826390375,pitch=42.146633,yaw=90.13701)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.45276798785401,z=191.37664826390375,pitch=41.99663,yaw=90.13701)
16-02-07 19:23:03 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.53116798937989, 191.37664826390375
to: -423.48035049357446, 44.45276798785401, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-1.302977000006099,0.0)
16-02-07 19:23:03 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:03 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.078 / -0.078, sby=44.53116798937989 (-0.078 / 0.0)
 tags: data_missing

16-02-07 19:23:03 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.46883205 / nf=0.54723203 (+0.5472320318222046) | ymax=44.53116798937989
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.29753598333741,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.45276798785401, 191.37664826390375
to: -423.48035049357446, 44.29753598333741, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-1.35531748638417,0.0)
16-02-07 19:23:03 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:03 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.155 / 0, sby=44.45276798785401 (-0.155 / 0.0)
 tags: data_missing+vdistrel

16-02-07 19:23:03 [INFO] [VL] [MOVING_SURVIVALFLY] [tssge] VL=200.9(+15.5) distance=0.16 health=20.0/20.0 locationfrom=-423.48, 44.45, 191.38 locationto=-423.48, 44.30, 191.38 tags=data_missing+vdistrel
16-02-07 19:23:03 [FINE] [MOVING] [tssge] Set back to: CraftWorld{name=world}-423.48, 44.453, 191.377
16-02-07 19:23:03 [FINE] [MOVING] [tssge] TP UNKNOWN (set-back): Location{world=CraftWorld{name=world},x=-423.48035049357446,y=44.45276798785401,z=191.37664826390375,pitch=41.99663,yaw=90.13701}
16-02-07 19:23:03 [FINE] [NET] [tssge] Expect ACK on outgoing position: CountableLocation(x=-423.48035049357446,y=44.45276798785401,z=191.37664826390375,pitch=41.99663,yaw=90.13701,count=1)
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.067008614424445,z=191.37664826390375)
16-02-07 19:23:03 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.45276798785401, 191.37664826390375
to: -423.48035049357446, 44.067008614424445, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-1.35531748638417,0.0)
16-02-07 19:23:03 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:03 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.386 / 0, sby=44.45276798785401 (-0.386 / 0.0)
 tags: data_reset+vdistrel

16-02-07 19:23:03 [INFO] [VL] [MOVING_SURVIVALFLY] [tssge] VL=239.4(+38.6) distance=0.39 health=20.0/20.0 locationfrom=-423.48, 44.45, 191.38 locationto=-423.48, 44.07, 191.38 tags=data_reset+vdistrel
16-02-07 19:23:03 [FINE] [MOVING] [tssge] Set back to: CraftWorld{name=world}-423.48, 44.453, 191.377
16-02-07 19:23:03 [FINE] [MOVING] [tssge] TP UNKNOWN (set-back): Location{world=CraftWorld{name=world},x=-423.48035049357446,y=44.45276798785401,z=191.37664826390375,pitch=41.99663,yaw=90.13701}
16-02-07 19:23:03 [FINE] [NET] [tssge] Expect ACK on outgoing position: CountableLocation(x=-423.48035049357446,y=44.45276798785401,z=191.37664826390375,pitch=41.99663,yaw=90.13701,count=2)
16-02-07 19:23:03 [FINE] [NET] [tssge] Incoming packet, interpret as ACK for outgoing position.
16-02-07 19:23:03 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.45276798785401,z=191.37664826390375,pitch=41.99663,yaw=90.13701)
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.45276798785401,z=191.37664826390375)
16-02-07 19:23:04 [FINE] [NET] [tssge] Incoming packet, interpret as ACK for outgoing position.
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.45276798785401,z=191.37664826390375,pitch=41.99663,yaw=90.13701)
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false)
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.37436798632813,z=191.37664826390375)
16-02-07 19:23:04 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.45276798785401, 191.37664826390375
to: -423.48035049357446, 44.37436798632813, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.1552320045166016,0.0)
16-02-07 19:23:04 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:04 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.078 / -0.078, sby=44.45276798785401 (-0.078 / 0.0)
 tags: data_missing

16-02-07 19:23:04 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.54723203 / nf=0.62563205 (+0.6256320476531982) | ymax=44.45276798785401
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.21913598181153,z=191.37664826390375)
16-02-07 19:23:04 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.37436798632813, 191.37664826390375
to: -423.48035049357446, 44.21913598181153, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.230527368912964,0.0)
16-02-07 19:23:04 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:04 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.155 / 0, sby=44.37436798632813 (-0.155 / 0.0)
 tags: data_missing+vdistrel

16-02-07 19:23:04 [INFO] [VL] [MOVING_SURVIVALFLY] [tssge] VL=255(+15.5) distance=0.16 health=20.0/20.0 locationfrom=-423.48, 44.37, 191.38 locationto=-423.48, 44.22, 191.38 tags=data_missing+vdistrel
16-02-07 19:23:04 [FINE] [MOVING] [tssge] Set back to: CraftWorld{name=world}-423.48, 44.374, 191.377
16-02-07 19:23:04 [FINE] [MOVING] [tssge] TP UNKNOWN (set-back): Location{world=CraftWorld{name=world},x=-423.48035049357446,y=44.37436798632813,z=191.37664826390375,pitch=41.99663,yaw=90.13701}
16-02-07 19:23:04 [FINE] [NET] [tssge] Expect ACK on outgoing position: CountableLocation(x=-423.48035049357446,y=44.37436798632813,z=191.37664826390375,pitch=41.99663,yaw=90.13701,count=1)
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=43.98860861289857,z=191.37664826390375)
16-02-07 19:23:04 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.37436798632813, 191.37664826390375
to: -423.48035049357446, 43.98860861289857, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.230527368912964,0.0)
16-02-07 19:23:04 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to below id=98 data=3 shape=[0.0, 0.0, 0.0, 1.0, 1.0, 1.0]
16-02-07 19:23:04 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.386 / 0, sby=44.37436798632813 (-0.386 / 0.0)
 tags: data_reset+vdistrel

16-02-07 19:23:04 [INFO] [VL] [MOVING_SURVIVALFLY] [tssge] VL=293.5(+38.6) distance=0.39 health=20.0/20.0 locationfrom=-423.48, 44.37, 191.38 locationto=-423.48, 43.99, 191.38 tags=data_reset+vdistrel
16-02-07 19:23:04 [FINE] [MOVING] [tssge] Set back to: CraftWorld{name=world}-423.48, 44.374, 191.377
16-02-07 19:23:04 [FINE] [MOVING] [tssge] TP UNKNOWN (set-back): Location{world=CraftWorld{name=world},x=-423.48035049357446,y=44.37436798632813,z=191.37664826390375,pitch=41.99663,yaw=90.13701}
16-02-07 19:23:04 [FINE] [NET] [tssge] Expect ACK on outgoing position: CountableLocation(x=-423.48035049357446,y=44.37436798632813,z=191.37664826390375,pitch=41.99663,yaw=90.13701,count=2)
16-02-07 19:23:04 [FINE] [NET] [tssge] Incoming packet, interpret as ACK for outgoing position.
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.37436798632813,z=191.37664826390375,pitch=41.99663,yaw=90.13701)
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.37436798632813,z=191.37664826390375)
16-02-07 19:23:04 [FINE] [NET] [tssge] Incoming packet, interpret as ACK for outgoing position.
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.37436798632813,z=191.37664826390375,pitch=41.99663,yaw=90.13701)
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false)
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.29596798480225,z=191.37664826390375)
16-02-07 19:23:04 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.37436798632813, 191.37664826390375
to: -423.48035049357446, 44.29596798480225, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.5169479491049732,0.0)
16-02-07 19:23:04 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:04 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.078 / -0.078, sby=44.37436798632813 (-0.078 / 0.0)
 tags: data_missing

16-02-07 19:23:04 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.62563205 / nf=0.70403206 (+0.7040320634841919) | ymax=44.37436798632813
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.140735980285655,z=191.37664826390375)
16-02-07 19:23:04 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.29596798480225, 191.37664826390375
to: -423.48035049357446, 44.140735980285655, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.5850090015087522,0.0)
16-02-07 19:23:04 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:04 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.155 / 0, sby=44.29596798480225 (-0.155 / 0.0)
 tags: data_missing+vdistrel

16-02-07 19:23:04 [INFO] [VL] [MOVING_SURVIVALFLY] [tssge] VL=309.1(+15.5) distance=0.16 health=20.0/20.0 locationfrom=-423.48, 44.30, 191.38 locationto=-423.48, 44.14, 191.38 tags=data_missing+vdistrel
16-02-07 19:23:04 [FINE] [MOVING] [tssge] Set back to: CraftWorld{name=world}-423.48, 44.296, 191.377
16-02-07 19:23:04 [FINE] [MOVING] [tssge] TP UNKNOWN (set-back): Location{world=CraftWorld{name=world},x=-423.48035049357446,y=44.29596798480225,z=191.37664826390375,pitch=41.99663,yaw=90.13701}
16-02-07 19:23:04 [FINE] [NET] [tssge] Expect ACK on outgoing position: CountableLocation(x=-423.48035049357446,y=44.29596798480225,z=191.37664826390375,pitch=41.99663,yaw=90.13701,count=1)
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=43.91020861137269,z=191.37664826390375)
16-02-07 19:23:04 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.29596798480225, 191.37664826390375
to: -423.48035049357446, 43.91020861137269, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.5850090015087522,0.0)
16-02-07 19:23:04 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to below id=98 data=3 shape=[0.0, 0.0, 0.0, 1.0, 1.0, 1.0]
16-02-07 19:23:04 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.386 / 0, sby=44.29596798480225 (-0.386 / 0.0)
 tags: data_reset+vdistrel

16-02-07 19:23:04 [INFO] [VL] [MOVING_SURVIVALFLY] [tssge] VL=347.6(+38.6) distance=0.39 health=20.0/20.0 locationfrom=-423.48, 44.30, 191.38 locationto=-423.48, 43.91, 191.38 tags=data_reset+vdistrel
16-02-07 19:23:04 [FINE] [MOVING] [tssge] Set back to: CraftWorld{name=world}-423.48, 44.296, 191.377
16-02-07 19:23:04 [FINE] [MOVING] [tssge] TP UNKNOWN (set-back): Location{world=CraftWorld{name=world},x=-423.48035049357446,y=44.29596798480225,z=191.37664826390375,pitch=41.99663,yaw=90.13701}
16-02-07 19:23:04 [FINE] [NET] [tssge] Expect ACK on outgoing position: CountableLocation(x=-423.48035049357446,y=44.29596798480225,z=191.37664826390375,pitch=41.99663,yaw=90.13701,count=2)
16-02-07 19:23:04 [FINE] [NET] [tssge] Incoming packet, interpret as ACK for outgoing position.
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.29596798480225,z=191.37664826390375,pitch=41.99663,yaw=90.13701)
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.29596798480225,z=191.37664826390375)
16-02-07 19:23:04 [FINE] [NET] [tssge] Incoming packet, interpret as ACK for outgoing position.
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.29596798480225,z=191.37664826390375,pitch=41.99663,yaw=90.13701)
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false)
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.217567983276375,z=191.37664826390375)
16-02-07 19:23:04 [FINE] [MOVING] [tssge] MOVE in world world:
from: -423.48035049357446, 44.29596798480225, 191.37664826390375
to: -423.48035049357446, 44.217567983276375, 191.37664826390375
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.8439105457704985,0.0)
16-02-07 19:23:04 [FINE]
from id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
to id=119 data=0 shape=[0.0, 0.0, 0.0, 1.0, 0.0625, 1.0]
16-02-07 19:23:04 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 0, liftoff: UNKNOWN(0)
 hDist: 0 / 0 hbuf=0 , vDist: -0.078 / -0.078, sby=44.29596798480225 (-0.078 / 0.0)
 tags: data_missing

16-02-07 19:23:04 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.70403206 / nf=0.7824321 (+0.7824320793151855) | ymax=44.29596798480225
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=44.062335978759776,z=191.37664826390375)
16-02-07 19:23:04 [FINE] [MOVING] [tssge] TP PLUGIN (normal): Location{world=CraftWorld{name=world},x=-414.11116434162534,y=44.5,z=190.97820095346745,pitch=5.2466393,yaw=83.087036}
16-02-07 19:23:04 [FINE] [NET] [tssge] Expect ACK on outgoing position: CountableLocation(x=-414.11116434162534,y=44.5,z=190.97820095346745,pitch=5.2466393,yaw=83.087036,count=1)
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-423.48035049357446,y=43.83180860984681,z=191.37664826390375)
16-02-07 19:23:04 [FINE] [NET] [tssge] Incoming packet, interpret as ACK for outgoing position.
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-414.11116434162534,y=44.5,z=190.97820095346745,pitch=5.2466393,yaw=83.087036)
16-02-07 19:23:04 [FINE] [NET] [tssge] Flying(ground=false,x=-414.11116434162534,y=44.5,z=190.97820095346745,pitch=5.2466393,yaw=83.087036)
`
Norma portal:
`16-02-07 19:24:05 [FINE] [MOVING] [tssge] Split move 1 (from -> loc):
16-02-07 19:24:05 [FINE] [MOVING] [tssge] MOVE in world world:
Location: -425.59185166779105, 45.0, 192.70449832288537
from: -425.5911441943598, 45.0, 192.73608216886728
to: -425.59185166779105, 45.0, 192.70449832288537
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.0784000015258789,0.0)
16-02-07 19:24:05 [FINE]
from flags: STAIRS+SOLID+GROUND+HEIGHT100+XZ100+GROUND_HEIGHT
from below id=90 data=1 shape=[0.0, 0.0, 0.375, 1.0, 1.0, 0.625]
to flags: STAIRS+SOLID+GROUND+HEIGHT100+XZ100+GROUND_HEIGHT
to below id=90 data=1 shape=[0.0, 0.0, 0.375, 1.0, 1.0, 0.625]
16-02-07 19:24:05 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: onground -> onground, jumpphase: 0, liftoff: NORMAL(35)
 hDist: 0.032(-0.032) / 0.287 , vDist: 0 (0) / 0.6, sby=45.0 (0 / 1.35)

16-02-07 19:24:05 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.0 / nf=0.0 | ymax=45.0
16-02-07 19:24:05 [FINE] [MOVING] [tssge] Split move 2 (loc -> to):
16-02-07 19:24:05 [FINE] [MOVING] [tssge] MOVE in world world:
from: -425.59185166779105, 45.0, 192.70449832288537
to: -425.59136309701614, 45.0, 192.6064995473436
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.0784000015258789,0.0)
16-02-07 19:24:05 [FINE]
from flags: STAIRS+SOLID+GROUND+HEIGHT100+XZ100+GROUND_HEIGHT
from below id=90 data=1 shape=[0.0, 0.0, 0.375, 1.0, 1.0, 0.625]
to below id=90 data=1 shape=[0.0, 0.0, 0.375, 1.0, 1.0, 0.625]
16-02-07 19:24:05 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: onground -> ---, jumpphase: 0, liftoff: NORMAL(36)
 hDist: 0.098(+0.066) / 0.287 , vDist: 0 (0) / 0.425, sby=45.0 (0 / 1.35)

16-02-07 19:24:05 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.0 / nf=0.0 | ymax=45.0
16-02-07 19:24:05 [FINE] [NET] [tssge] Flying(ground=false,x=-425.59087452624124,y=44.92159999847412,z=192.454993434141)
16-02-07 19:24:05 [FINE] [MOVING] [tssge] MOVE in world world:
from: -425.59136309701614, 45.0, 192.6064995473436
to: -425.59087452624124, 44.92159999847412, 192.454993434141
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.0784000015258789,0.0)
16-02-07 19:24:05 [FINE]
from below id=90 data=1 shape=[0.0, 0.0, 0.375, 1.0, 1.0, 0.625]
to id=90 data=1 shape=[0.0, 0.0, 0.375, 1.0, 1.0, 0.625]
16-02-07 19:24:05 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 1, liftoff: NORMAL(0)
 hDist: 0.152(+0.054) / 0.287 , vDist: -0.078 (-0.078) / -0.062, sby=45.0 (-0.078 / 1.35)
 tags: ychdec

16-02-07 19:24:05 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.0 / nf=0.0784 (+0.07840000092983246) | ymax=45.0
16-02-07 19:24:05 [FINE] [NET] [tssge] Flying(ground=false,x=-425.59087452624124,y=44.76636799395752,z=192.37227108672394)
16-02-07 19:24:05 [FINE] [MOVING] [tssge] MOVE in world world:
from: -425.59087452624124, 44.92159999847412, 192.454993434141
to: -425.59087452624124, 44.76636799395752, 192.37227108672394
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.1552320045166016,0.0)
16-02-07 19:24:05 [FINE]
from id=90 data=1 shape=[0.0, 0.0, 0.375, 1.0, 1.0, 0.625]
to id=90 data=1 shape=[0.0, 0.0, 0.375, 1.0, 1.0, 0.625]
16-02-07 19:24:05 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 2, liftoff: NORMAL(0)
 hDist: 0.083(-0.069) / 0.287 , vDist: -0.155 (-0.077) / -0.139, sby=45.0 (-0.234 / 1.35)

16-02-07 19:24:05 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.0784 / nf=0.233632 (+0.1552319973707199) | ymax=45.0
16-02-07 19:24:05 [FINE] [NET] [tssge] Flying(ground=false,x=-425.59087452624124,y=44.53584062504456,z=192.29699374840496)
16-02-07 19:24:05 [FINE] [MOVING] [tssge] MOVE in world world:
from: -425.59087452624124, 44.76636799395752, 192.37227108672394
to: -425.59087452624124, 44.53584062504456, 192.29699374840496
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.230527368912964,0.0)
16-02-07 19:24:05 [FINE]
from id=90 data=1 shape=[0.0, 0.0, 0.375, 1.0, 1.0, 0.625]
to id=90 data=1 shape=[0.0, 0.0, 0.375, 1.0, 1.0, 0.625]
16-02-07 19:24:05 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 3, liftoff: NORMAL(0)
 hDist: 0.075(-0.007) / 0.287 , vDist: -0.231 (-0.075) / -0.215, sby=45.0 (-0.464 / 1.35)

16-02-07 19:24:05 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.233632 / nf=0.46415937 (+0.2305273711681366) | ymax=45.0
16-02-07 19:24:05 [FINE] [NET] [tssge] Flying(ground=false,x=-425.59087452624124,y=44.231523797587016,z=192.22849136856044)
16-02-07 19:24:05 [FINE] [MOVING] [tssge] MOVE in world world:
from: -425.59087452624124, 44.53584062504456, 192.29699374840496
to: -425.59087452624124, 44.231523797587016, 192.22849136856044
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.30431682745754424,0.0)
16-02-07 19:24:05 [FINE]
from id=90 data=1 shape=[0.0, 0.0, 0.375, 1.0, 1.0, 0.625]
to id=90 data=1 shape=[0.0, 0.0, 0.375, 1.0, 1.0, 0.625]
16-02-07 19:24:05 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 4, liftoff: NORMAL(0)
 hDist: 0.069(-0.007) / 0.287 , vDist: -0.304 (-0.074) / -0.288, sby=45.0 (-0.768 / 1.35)
 vacc=|-0.304/1|-0.464/3|0/0|

16-02-07 19:24:05 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.46415937 / nf=0.7684762 (+0.30431681871414185) | ymax=45.0
16-02-07 19:24:05 [FINE] [NET] [tssge] Flying(ground=false,x=-425.59087452624124,y=43.85489329934836,z=192.1661542011054)
16-02-07 19:24:05 [FINE] [MOVING] [tssge] MOVE in world world:
from: -425.59087452624124, 44.231523797587016, 192.22849136856044
to: -425.59087452624124, 43.85489329934836, 192.1661542011054
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.37663049823865513,0.0)
16-02-07 19:24:05 [FINE]
from id=90 data=1 shape=[0.0, 0.0, 0.375, 1.0, 1.0, 0.625]
to below id=98 data=0 shape=[0.0, 0.0, 0.0, 1.0, 1.0, 1.0]
16-02-07 19:24:05 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 5, liftoff: NORMAL(0)
 hDist: 0.062(-0.006) / 0.287 , vDist: -0.377 (-0.072) / -0.361, sby=45.0 (-1.145 / 1.35)
 vacc=|-0.681/2|-0.464/3|0/0|

16-02-07 19:24:05 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.7684762 / nf=1.1451067 (+0.3766304850578308) | ymax=45.0
16-02-07 19:24:05 [FINE] [NET] [tssge] Flying(ground=false,x=-425.59087452624124,y=43.40739540236494,z=192.10942737708646)
16-02-07 19:24:05 [FINE] [MOVING] [tssge] MOVE in world world:
from: -425.59087452624124, 43.85489329934836, 192.1661542011054
to: -425.59087452624124, 43.40739540236494, 192.10942737708646
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.44749789698341763,0.0)
16-02-07 19:24:05 [FINE]
from below id=98 data=0 shape=[0.0, 0.0, 0.0, 1.0, 1.0, 1.0]
to flags: SOLID+GROUND
to below id=98 data=0 shape=[0.0, 0.0, 0.0, 1.0, 1.0, 1.0] (ground within 0.5)
16-02-07 19:24:05 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> ---, jumpphase: 6, liftoff: NORMAL(0)
 hDist: 0.057(-0.006) / 0.287 , vDist: -0.447 (-0.071) / -0.431, sby=45.0 (-1.593 / 1.35)
 vacc=|-1.128/3|-0.464/3|0/0|

16-02-07 19:24:05 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=1.1451067 / nf=1.5926045 (+0.4474978446960449) | ymax=45.0
16-02-07 19:24:05 [FINE] [NET] [tssge] Flying(ground=true,x=-425.59087452624124,y=43.0,z=192.0578059657415)
16-02-07 19:24:05 [FINE] [MOVING] [tssge] MOVE in world world:
from: -425.59087452624124, 43.40739540236494, 192.10942737708646
to: -425.59087452624124, 43.0, 192.0578059657415
(walkspeed=0.2 flyspeed=0.1)(svel=0.0,-0.5169479491049732,0.0)
16-02-07 19:24:05 [FINE]
from flags: SOLID+GROUND
from below id=98 data=0 shape=[0.0, 0.0, 0.0, 1.0, 1.0, 1.0] (ground within 0.5)
to flags: SOLID+GROUND
to below id=98 data=0 shape=[0.0, 0.0, 0.0, 1.0, 1.0, 1.0]
16-02-07 19:24:05 [FINE] [MOVING_SURVIVALFLY] [tssge]
onground: --- -> onground, jumpphase: 7, liftoff: NORMAL(0)
 hDist: 0.052(-0.005) / 0.287 , vDist: -0.407 (+0.04) / -0.501, sby=45.0 (-2 / 1.35)

16-02-07 19:24:05 [FINE] [MOVING_NOFALL] [tssge] NoFall: mc=0.0 / nf=0.0 | ymax=43.40739540236494
16-02-07 19:24:05 [FINE] [NET] [tssge] Flying(ground=true,x=-425.59087452624124,y=43.0,z=192.01083048006376)
16-02-07 19:24:05 [FINE] [NET] [tssge] Flying(ground=true)
`

**Comment by asofold** [comment]
@tssge Thank you for the debug log, this will help nailing it down. (Could you still consider putting the lengthy logs into a gist rather and link the gist from your post? 'ncp version' is better to have directly here, but long logs are easier to follow with a gist/paste.)

The first violation shows 'data missing'. This means that the player data is not present for the player, and could mean
* 'ncp remove ...' or 'ncp reload' has been called or a plugin removed the data 'compatibility' or 'cleanup' (problematic). With on-the-fly debugging it wouldn't log on after reload or data removal, though.
* The player name changed. Doesn't seem to be the case.
* The system time ran backwards (currently all data is removed then, which is not good either). This doesn't seem to be the case as it should be logged to the file as well.

So i'd ask:
* Are there tasks or plugins removing data of online players?
* Could you check the server log for "system time ran backwards"?

**Comment by asofold** [comment]
Could you re-test with build 928?

**Comment by tssge** [comment]
Amazing! I ran tests with build 928 and it seems that the issue is resolved. I cannot reproduce the issue anymore with that new build.

However, I don't understand yet how that commit (https://github.com/NoCheatPlus/NoCheatPlus/commit/f6a004015dac51fb0a8e8805ba73f9ad044e38c4) fixed the bug, as our system's time does not run backwards. I'm going to go through the code to understand it a bit.

Thank you a lot for a fast response time on this!

**Comment by PhanaticD** [comment]
yes it is fixed for me as well on 928

**Comment by asofold** [comment]
@PhanaticD @tssge Thank you for the feedback.

@tssge That commit actually did not fix it, though it might fix occasional false positives with system time running backwards, for those servers that have that issue at all. If this was the cause it would really get logged and appear in the trace file output you've posted above. I just took this opportunity to think about time running backwards and to bring in a new map type for internals - so you're actually alpha testing that one :p. Related topics will be 'how to reset temporary debug flags without data removal nor ncp reload' and similar things.

The commit that fixed it should in this case be: https://github.com/NoCheatPlus/NoCheatPlus/commit/302b1ec824257021f449ec59a5f4526c7b9de3da

The portals lead to a loop of data removal - that's one of the spots i missed on the transition to past move tracking. The portal events should be followed by a teleport event anyway, so i might fully remove the data resetting there. For now i've changed it to just do without data resetting, in case there is no target location set (possibly virtually always). Plus portal events should be debug-logged somehow, might be lots/second though.

**Comment by SwiftSwamp** [comment]
I can confirm that this resolved the issue for me as well, also props to you for replying so quickly and showing the exact code that fixed it.

**Comment by asofold** [comment]
Looks like debug logs win out most of the time for moving checks :).

**Comment by afroman84** [comment]
Hello, it seems i have this issue but on the latest development version #1022 (using latest paper spigot).
This is what the log reports:
`16-10-31 17:36:18 [INFO] (CONSOLE) Kicked Afroman : Tried to move unexpectedly!
16-10-31 17:36:30 [WARNING] [MOVING] [Afroman]  TP UNKNOWN (set-back was overridden): Location{world=CraftWorld{name=world_the_end},x=-586.1477091341195,y=35.60739545004866,z=-20586.873165719076,pitch=26.400316,yaw=288.30798}
16-10-31 17:39:37 [INFO] (CONSOLE) Kicked Afroman : Tried to move unexpectedly!
16-10-31 17:40:01 [WARNING] [MOVING] [Afroman]  TP UNKNOWN (set-back was overridden): Location{world=CraftWorld{name=world_the_end},x=-586.3510289421503,y=35.53584062504456,z=-20586.384915394046,pitch=35.699997,yaw=-81.41359}
16-10-31 17:44:22 [INFO] (CONSOLE) Kicked Afroman : Tried to move unexpectedly!
16-10-31 17:45:08 [WARNING] [MOVING] [Afroman]  TP UNKNOWN (set-back was overridden): Location{world=CraftWorld{name=world_the_end},x=-586.3901683639717,y=35.53584062504456,z=-20586.347577422555,pitch=20.100014,yaw=276.18625}
`
is there something to change in the config.yml apart of disabling the moving check?

**Comment by asofold** [comment]
@afroman84 

Looks like a special case or at least an unintended sequence of things, as the "set-back was overridden" indicates.

Could you provide more of the log from slightly before? Also server log entries from around that time could be interesting.

**Comment by afroman84** [comment]
@asofold 

1. server log: http://pastebin.com/ff0Mac3a
    ncp log: http://pastebin.com/QsafHu5Z

2. server log: http://pastebin.com/1Aa23u2c
    ncp log: http://pastebin.com/671S3P0k

3. server log: http://pastebin.com/JL4Lm6P5
    ncp log:  http://pastebin.com/Xm3iXfn3

i hope this is useful.
meanwhile i had to disable the survivalfly and moving check  :(

**Comment by asofold** [comment]
Could you create a debug log for one player?
https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players

This could reveal what is happening in more detail.

**Comment by afroman84** [comment]
@asofold 
NCP log: https://paste.ee/p/EYtt3
Server log: https://paste.ee/p/4x7VF

if you need more logs please ask, actually i had to disable SurvivalFly and moving checks.
this is my actual NCP config: http://pastebin.com/rfDMaJfc

**Comment by asofold** [comment]
Thank you very much!

Looks like the same issue as this one: https://github.com/NoCheatPlus/Issues/issues/221
I suggest upvoting that one and to continue there.

The log seems to confirm issues with the first move in the end containing current location and move end point reflecting the position from the world they teleported from. This clearly is a server side bug, but we might be able to add some workaround for this, as people seem to have trouble fixing it.
